// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MerkleProof$Type } from "./MerkleProof";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MerkleProof"]: MerkleProof$Type;
    ["@openzeppelin/contracts/utils/cryptography/MerkleProof.sol:MerkleProof"]: MerkleProof$Type;
  }

  interface ContractTypesMap {
    ["MerkleProof"]: GetContractReturnType<MerkleProof$Type["abi"]>;
    ["@openzeppelin/contracts/utils/cryptography/MerkleProof.sol:MerkleProof"]: GetContractReturnType<MerkleProof$Type["abi"]>;
  }
}
