// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface MerkleProof$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "MerkleProof",
  "sourceName": "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol",
  "abi": [
    {
      "inputs": [],
      "name": "MerkleProofInvalidMultiproof",
      "type": "error"
    }
  ],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220713cc22a7b971b8f4135c1eb9dbd6014f3bd70bc7884e02fe6a4c0597086ec3064736f6c63430008140033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220713cc22a7b971b8f4135c1eb9dbd6014f3bd70bc7884e02fe6a4c0597086ec3064736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "MerkleProof",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MerkleProof$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol:MerkleProof",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<MerkleProof$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "MerkleProof",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MerkleProof$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol:MerkleProof",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<MerkleProof$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "MerkleProof",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MerkleProof$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol:MerkleProof",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<MerkleProof$Type["abi"]>>;
}
