// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Hashes$Type } from "./Hashes";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Hashes"]: Hashes$Type;
    ["@openzeppelin/contracts/utils/cryptography/Hashes.sol:Hashes"]: Hashes$Type;
  }

  interface ContractTypesMap {
    ["Hashes"]: GetContractReturnType<Hashes$Type["abi"]>;
    ["@openzeppelin/contracts/utils/cryptography/Hashes.sol:Hashes"]: GetContractReturnType<Hashes$Type["abi"]>;
  }
}
