// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import type { Address } from "viem";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";
import "@nomicfoundation/hardhat-viem/types";

export interface Hashes$Type {
  "_format": "hh-sol-artifact-1",
  "contractName": "Hashes",
  "sourceName": "@openzeppelin/contracts/utils/cryptography/Hashes.sol",
  "abi": [],
  "bytecode": "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212200939f07f27ef8664c879f4d2eba5aceafe69bca7f30d5d9941dab9a91615d3d264736f6c63430008140033",
  "deployedBytecode": "0x73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212200939f07f27ef8664c879f4d2eba5aceafe69bca7f30d5d9941dab9a91615d3d264736f6c63430008140033",
  "linkReferences": {},
  "deployedLinkReferences": {}
}

declare module "@nomicfoundation/hardhat-viem/types" {
  export function deployContract(
    contractName: "Hashes",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Hashes$Type["abi"]>>;
  export function deployContract(
    contractName: "@openzeppelin/contracts/utils/cryptography/Hashes.sol:Hashes",
    constructorArgs?: [],
    config?: DeployContractConfig
  ): Promise<GetContractReturnType<Hashes$Type["abi"]>>;

  export function sendDeploymentTransaction(
    contractName: "Hashes",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Hashes$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;
  export function sendDeploymentTransaction(
    contractName: "@openzeppelin/contracts/utils/cryptography/Hashes.sol:Hashes",
    constructorArgs?: [],
    config?: SendDeploymentTransactionConfig
  ): Promise<{
    contract: GetContractReturnType<Hashes$Type["abi"]>;
    deploymentTransaction: GetTransactionReturnType;
  }>;

  export function getContractAt(
    contractName: "Hashes",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Hashes$Type["abi"]>>;
  export function getContractAt(
    contractName: "@openzeppelin/contracts/utils/cryptography/Hashes.sol:Hashes",
    address: Address,
    config?: GetContractAtConfig
  ): Promise<GetContractReturnType<Hashes$Type["abi"]>>;
}
