// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { MultiMerkleStash$Type } from "./MultiMerkleStash";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["MultiMerkleStash"]: MultiMerkleStash$Type;
    ["contracts/MultiMerkleStash.sol:MultiMerkleStash"]: MultiMerkleStash$Type;
  }

  interface ContractTypesMap {
    ["MultiMerkleStash"]: GetContractReturnType<MultiMerkleStash$Type["abi"]>;
    ["contracts/MultiMerkleStash.sol:MultiMerkleStash"]: GetContractReturnType<MultiMerkleStash$Type["abi"]>;
  }
}
