name: "All Protocol Bounties"

on:
  workflow_dispatch:
    inputs:
      pastWeek:
        description: "Number of weeks in the past (0 for current week)"
        required: true
        default: "0"
      chain:
        description: "Chain to check for claimed bounties"
        required: true
        type: choice
        options:
          - mainnet
          - bsc
  schedule:
    - cron: "0 19 * * 4"

jobs:
  votemarket:
    uses: ./.github/workflows/votemarket-bounties.yaml
    with:
      pastWeek: ${{ github.event.inputs.pastWeek || '0' }}
      chain: ${{ github.event.inputs.chain || 'mainnet' }}
    secrets: inherit

  votemarket-v2:
    uses: ./.github/workflows/votemarket-v2-bounties.yaml
    with:
      pastWeek: ${{ github.event.inputs.pastWeek || '0' }}
      chain: ${{ github.event.inputs.chain || 'mainnet' }}
    secrets: inherit

  warden:
    uses: ./.github/workflows/warden-bounties.yaml
    with:
      pastWeek: ${{ github.event.inputs.pastWeek || '0' }}
      chain: ${{ github.event.inputs.chain || 'mainnet' }}
    secrets: inherit

  hiddenhand:
    uses: ./.github/workflows/hiddenhand-bounties.yaml
    with:
      pastWeek: ${{ github.event.inputs.pastWeek || '0' }}
      chain: ${{ github.event.inputs.chain || 'mainnet' }}
    secrets: inherit 