name: "[Spectra] Merkle - Copy to latest"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [copy-spectra-merkle]

jobs:
  generate-merkles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Copy Spectra merkle
        run: |
          # Calculate current period
          WEEK=604800
          CURRENT_TIMESTAMP=$(date +%s)
          CURRENT_PERIOD=$(( CURRENT_TIMESTAMP / WEEK * WEEK ))

          cp "${GITHUB_WORKSPACE}/bounties-reports/latest/spectra/merkle_data_tmp.json" "${GITHUB_WORKSPACE}/bounties-reports/latest/spectra_merkle.json"
          cp "${GITHUB_WORKSPACE}/bounties-reports/${CURRENT_PERIOD}/delegationsAPRs.json" "${GITHUB_WORKSPACE}/bounties-reports/delegationsAPRs.json"
          rm "${GITHUB_WORKSPACE}/bounties-reports/latest/spectra/merkle_data_tmp.json"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update Spectra merkle to latest"
