name: "[Spectra] Merkle - Copy to latest"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [copy-spectra-merkle]

jobs:
  generate-merkles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Copy Spectra merkle
        run: |
          cp "${GITHUB_WORKSPACE}/bounties-reports/latest/spectra/merkle_data_tmp.json" "${GITHUB_WORKSPACE}/bounties-reports/latest/spectra/merkle_data.json"
          rm "${GITHUB_WORKSPACE}/bounties-reports/latest/spectra/merkle_data_tmp.json"

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update Spectra merkle"
