name: "[System] Index - Delegator Logs"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 4" # Runs every Thursday at 00:00 UTC

jobs:
  index-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Configure git and pull latest changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git pull origin main --rebase

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"

      - name: Run indexer
        run: make -f automation/indexer.mk get-delegators
        env:
          EXPLORER_KEY: ${{ secrets.ETHERSCAN_TOKEN }}
          WEB3_ALCHEMY_API_KEY: ${{ secrets.WEB3_ALCHEMY_API_KEY }}

      - name: Commit and push changes
        run: make -f automation/indexer.mk commit-and-push

      - name: Clean up
        if: always()
        run: make -f automation/indexer.mk clean

      - name: Send error notification to Telegram
        if: failure()
        uses: appleboy/telegram-action@v1.0.1
        with:
          to: -1002354704686
          token: ${{ secrets.TG_API_KEY_BOT_ERROR }}
          format: html
          message: |
            ❌ <b>Workflow failed</b>
            • <b>Workflow:</b> ${{ github.workflow }}
            • <b>Job:</b> index-logs
            • <b>Trigger:</b> ${{ github.event_name }}
            • <b>Status:</b> ${{ job.status }}
            📋 <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">View workflow logs</a>
