name: "[sdTokens] Reports checker"

on:
  workflow_dispatch:
    inputs:
      protocol:
        description: 'Protocol to check'
        required: true
        type: choice
        options:
        - curve
        - balancer
        - fxn
        - frax
        - pendle
        - cake
        default: 'curve'
  repository_dispatch:
    types: [trigger-reports-checker]

jobs:
  check-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.5.1"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3

      - name: Install node dependencies
        run: pnpm install

      - name: Set protocol value
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "PROTOCOL=${{ github.event.inputs.protocol }}" >> $GITHUB_ENV
          else
            echo "PROTOCOL=curve" >> $GITHUB_ENV
          fi

      - name: Run reportVerifier script
        run: pnpm tsx script/repartition/sdTkns/reportVerifier.ts ${{ env.PROTOCOL }}
        env:
          TELEGRAM_VERIF_API_KEY: ${{ secrets.TELEGRAM_VERIF_API_KEY }}
          TELEGRAM_VERIF_CHAT_ID: ${{ secrets.TELEGRAM_VERIF_CHAT_ID }}
