name: "Router for weekly bounties"

on:
  repository_dispatch:
    types:
      - update-votemarket-claims
      - update-votemarket-v2-claims
      - update-warden-claims
      - update-hiddenhand-claims
      - update-convex-claims
      - update-convex-v2-claims

jobs:
  process-bounties:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Bounty Type
        id: determine_bounty_type
        run: |
          if [ "${{ github.event.action }}" == "update-votemarket-claims" ]; then
            echo "bountyType=votemarket" >> $GITHUB_ENV
          elif [ "${{ github.event.action }}" == "update-votemarket-v2-claims" ]; then
            echo "bountyType=votemarket-v2" >> $GITHUB_ENV
          elif [ "${{ github.event.action }}" == "update-warden-claims" ]; then
            echo "bountyType=warden" >> $GITHUB_ENV
          elif [ "${{ github.event.action }}" == "update-hiddenhand-claims" ]; then
            echo "bountyType=hiddenhand" >> $GITHUB_ENV
          elif [ "${{ github.event.action }}" == "update-convex-claims" ]; then
            echo "bountyType=convex" >> $GITHUB_ENV
          elif [ "${{ github.event.action }}" == "update-convex-v2-claims" ]; then
            echo "bountyType=convex-v2" >> $GITHUB_ENV
          fi
      - name: Run Bounties Workflow
        uses: ./.github/workflows/weekly-bounties.yaml
        with:
          bountyType: ${{ env.bountyType }}
          pastWeek: ${{ github.event.client_payload.pastWeek || '0' }}
          chain: ${{ github.event.client_payload.chain || 'mainnet' }}