name: "[sdTokens] Universal Merkles"

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Which token merkle to generate'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - spectra
          - sdfxs
  repository_dispatch:
    types: [generate-spectra-merkle, generate-sdfxs-merkle, generate-all-sd-merkles]

jobs:
  generate-spectra-merkle:
    runs-on: ubuntu-latest
    if: |
      github.event.inputs.token == 'all' || 
      github.event.inputs.token == 'spectra' || 
      github.event.action == 'generate-spectra-merkle' ||
      github.event.action == 'generate-all-sd-merkles'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.5.1"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3

      - name: Run Spectra merkle generation
        run: make -f automation/spectra/run.mk run-all
        env:
          EXPLORER_KEY: ${{ secrets.ETHERSCAN_TOKEN }}
          WEB3_ALCHEMY_API_KEY: ${{ secrets.WEB3_ALCHEMY_API_KEY}}

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add all changes and commit
          git add .
          git commit -m "chore: Update Spectra merkles" || echo "No changes to commit"
          
          # Fetch and rebase
          git pull --rebase origin main
          
          # Push changes
          git push origin main

      - name: Clean up
        if: always()
        run: make -f automation/spectra/run.mk clean

  generate-sdfxs-merkle:
    runs-on: ubuntu-latest
    needs: generate-spectra-merkle
    if: |
      always() && 
      (needs.generate-spectra-merkle.result == 'success' || needs.generate-spectra-merkle.result == 'skipped') &&
      (github.event.inputs.token == 'all' || 
       github.event.inputs.token == 'sdfxs' || 
       github.event.action == 'generate-sdfxs-merkle' ||
       github.event.action == 'generate-all-sd-merkles')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.5.1"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.12.3

      - name: Run sdFXS merkle generation
        run: make -f automation/sdfxs/run.mk run-merkle
        env:
          EXPLORER_KEY: ${{ secrets.ETHERSCAN_TOKEN }}
          WEB3_ALCHEMY_API_KEY: ${{ secrets.WEB3_ALCHEMY_API_KEY}}

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add all changes and commit
          git add .
          git commit -m "chore: Update sdFXS merkles" || echo "No changes to commit"
          
          # Fetch and rebase
          git pull --rebase origin main
          
          # Push changes
          git push origin main

      - name: Clean up
        if: always()
        run: make -f automation/sdfxs/run.mk clean