name: "Votemarket Claimed Bounties"

on:
  workflow_dispatch:
    inputs:
      pastWeek:
        description: "Number of weeks in the past (0 for current week)"
        required: true
        default: "0"
      chain:
        description: "Chain to check for claimed bounties"
        required: true
        type: choice
        options:
          - mainnet
          - bsc
  workflow_call:
    inputs:
      pastWeek:
        type: string
        required: false
        default: '0'
      chain:
        type: string
        required: false
        default: 'mainnet'
  schedule:
    - cron: "0 19 * * 4"

jobs:
  generate-votemarket-bounties:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"

      - name: Run generateVotemarket script
        run: |
          make -f automation/bounties.mk run-votemarket PAST_WEEK=${{ inputs.pastWeek || github.event.inputs.pastWeek || '0' }} CHAIN=${{ inputs.chain || github.event.inputs.chain || 'mainnet' }}
        env:
          EXPLORER_KEY: ${{ secrets.ETHERSCAN_TOKEN}}

      - name: Commit and push changes
        run: make -f automation/bounties.mk commit-and-push 