name: Generate Weekly Bounties

on:
  workflow_dispatch:
    inputs:
      pastWeek:
        description: 'Number of weeks in the past (0 for current week)'
        required: true
        default: '0'

jobs:
  generate-bounties:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      env:
        GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Run generateWeeklyBounties script
      run: |
        npx ts-node script/generateWeeklyBounties.ts ${{ github.event.inputs.pastWeek || '0' }}
      env:
        ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_TOKEN}}

    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add weekly-bounties
        git commit -m "Update weekly bounties" || exit 0
        git push