name: Generate Weekly Report (Bounties repartition)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * 0" # Runs every Sunday at 19:00 UTC

jobs:
  generate-bounties:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.5.1"

      - name: Install node dependencies
        run: yarn install

      - name: Run generateWeeklyReport script
        run: |
          npx ts-node script/generateWeeklyReport.ts
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_TOKEN}}

      - name: Commit and push if changed
        run: |
          git add .
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add weekly-bounties
          git commit -m "Update weekly report" || exit 0
          git push
