name: Generate Weekly Bounties

on:
  workflow_dispatch:
    inputs:
      pastWeek:
        description: "Number of weeks in the past (0 for current week)"
        required: true
        default: "0"
  schedule:
    - cron: "0 19 * * 4" # Runs every Thursday at 19:00 UTC

jobs:
  check-week:
    runs-on: ubuntu-latest
    outputs:
      isOdd: ${{ steps.week-check.outputs.isOdd }}
    steps:
      - name: Check if week is odd or even
        id: week-check
        run: |
          echo "isOdd=$(if (( $(date +'%V') % 2 )); then echo 'true'; else echo 'false'; fi)" >> $GITHUB_OUTPUT
        shell: bash

  generate-bounties:
    needs: check-week
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.5.1"

      - name: Install node dependencies
        run: yarn install

      - name: Run generateWeeklyBounties script
        run: |
          npx ts-node script/distribution/generateBounties.ts ${{ github.event.inputs.pastWeek || '0' }}
          npx ts-node script/distribution/generateBSCBounties.ts ${{ github.event.inputs.pastWeek || '0' }}
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_TOKEN}}

      - name: Run generateBSCBounties script (odd weeks only)
        if: ${{ github.event.inputs.pastWeek == '' && needs.check-week.outputs.isOdd == 'true' }}
        run: |
          npx ts-node script/generateBSCBounties.ts ${{ github.event.inputs.pastWeek || '0' }}
        env:
          BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_TOKEN}}

      - name: Commit and push if changed
        run: |
          git add .
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add weekly-bounties
          git commit -m "Update weekly bounties" || exit 0
          git push