name: Generate Weekly and OTC Reports

on:
  workflow_dispatch:
    inputs:
      actions:
        description: 'Actions to perform'
        required: true
        type: choice
        options:
        - Generate Ethereum reports
        - Generate OTCS reports
        default: 'Ethereum'
  schedule:
    - cron: "0 19 * * 4" # Runs every Thursday at 19:00 UTC

jobs:
  generate-reports:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.5.1"

      - name: Install node dependencies
        run: yarn install

      - name: Set actions
        id: set-actions
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "actions=Generate Ethereum reports" >> $GITHUB_OUTPUT
          else
            echo "actions=${{ github.event.inputs.actions }}" >> $GITHUB_OUTPUT
          fi

      - name: Run generateWeeklyReport script
        if: contains(steps.set-actions.outputs.actions, 'Generate Ethereum reports')
        run: |
          npx ts-node script/generateWeeklyReport.ts
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_TOKEN}}

      - name: Run generateOTCReport script
        if: contains(steps.set-actions.outputs.actions, 'Generate OTCS reports')
        run: |
          npx ts-node script/generateOTCReport.ts
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_TOKEN}}

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Update weekly bounties and OTC reports" || exit 0
          git push