name: "[sdTokens + vlCVX] Weekly claimed bounties"

on:
  workflow_dispatch:
    inputs:
      pastWeek:
        description: "Number of weeks in the past (0 for current week)"
        required: true
        default: "0"
      chain:
        description: "Chain to check for claimed bounties"
        required: true
        type: choice
        options:
          - mainnet
          - bsc
  schedule:
    - cron: "0 19 * * 4" # Runs every Thursday at 19:00 UTC

jobs:
  check-week:
    runs-on: ubuntu-latest
    outputs:
      isOdd: ${{ steps.week-check.outputs.isOdd }}
    steps:
      - name: Check if week is odd or even
        id: week-check
        run: |
          echo "isOdd=$(if (( $(date +'%V') % 2 )); then echo 'true'; else echo 'false'; fi)" >> $GITHUB_OUTPUT
        shell: bash

  generate-bounties:
    needs: check-week
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          GIT_ACCESS_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.13"

      - name: Run generateWeeklyBounties script
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.chain == 'mainnet' || github.event_name == 'schedule' }}
        run: |
          make -f automation/weekly-bounties.mk run-mainnet PAST_WEEK=${{ github.event.inputs.pastWeek || '0' }}
        env:
          EXPLORER_KEY: ${{ secrets.ETHERSCAN_TOKEN}}

      - name: Run generateBSCBounties script (odd weeks only)
        if: ${{ github.event_name == 'schedule' && needs.check-week.outputs.isOdd == 'true' || github.event_name == 'workflow_dispatch' && github.event.inputs.chain == 'bsc' }}
        run: |
          make -f automation/weekly-bounties.mk run-bsc PAST_WEEK=${{ github.event.inputs.pastWeek || '0' }}
        env:
          EXPLORER_KEY: ${{ secrets.ETHERSCAN_TOKEN}}

      - name: Commit and push changes
        run: make -f automation/weekly-bounties.mk commit-and-push

      - name: Clean up
        if: always()
        run: make -f automation/weekly-bounties.mk clean
